env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
   "import/extensions": [
      "error",
      "always",
      {
        "js": "always",
        "jsx": "always",
        "ts": "always",
        "tsx": "always"
      }
   ],
   'no-console': 'off',
}
